# Model arguments
model_name_or_path: meta-llama/Llama-3.1-8B
chat_template: "{% set loop_messages = messages %}{% for message in loop_messages %}{% set content = '<|start_header_id|>' + message['role'] + '<|end_header_id|>\n\n'+ message['content'] | trim + '<|eot_id|>' %}{% if loop.index0 == 0 %}{% set content = bos_token + content %}{% endif %}{{ content }}{% endfor %}{% if add_generation_prompt %}{{ '<|start_header_id|>assistant<|end_header_id|>\n\n' }}{% endif %}"
model_revision: main
torch_dtype: bfloat16
use_flash_attention_2: false

# Data training arguments
dataset_mixer:
  HuggingFaceH4/deita-10k-v0-sft: 1.0
dataset_splits:
- train_sft
- test_sft
preprocessing_num_workers: 12
packing: true

# SFT trainer config
bf16: true
dataset_kwargs:
  add_special_tokens: false
  append_concat_token: false
do_eval: true
evaluation_strategy: epoch
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 2.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: -1
num_train_epochs: 3
output_dir: ~/ADPA-OpenSource/data/llama3.2-1b-deita-dpomix/ref_teacher
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
push_to_hub: false
remove_unused_columns: true
report_to: none
save_strategy: "no"
seed: 42
warmup_ratio: 0.1